# https://github.com/KSPActions/reverse-rdssh-actions
# debugging only - @keepsobp

name: ubuntu-ssh
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  ubuntu-ssh:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
    steps:
    - name: Run establish a ngrok tunnel
      uses: vmactions/ngrok-tunnel@579a9626b87931d41492fbadcbec7453040ee080
      with:
        protocol: tcp
        port: 22
    - name: Change runner password
      run: |
         sudo apt-get update 
         echo 'runner:${{ secrets.PASSWORD }}' | sudo chpasswd
         echo 'runneradmin:${{ secrets.PASSWORD }}' | sudo chpasswd

    - run: |
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
           cat << EOF > ~/.ssh/config
           Host *
               ServerAliveInterval 60
               StrictHostKeyChecking no
           Host github.com
               User git
               Port 22
               Hostname github.com
               TCPKeepAlive yes
               IdentitiesOnly yes
           EOF
           sudo systemctl enable ssh.service
           sudo systemctl restart ssh.service
           sudo systemctl status ssh.service

    - name: sleep
      run: sleep 21600