name: ubuntu-vnc

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  ubuntu-vnc:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
    steps:
    - name: Run establish a ngrok tunnel
      uses: vmactions/ngrok-tunnel@579a9626b87931d41492fbadcbec7453040ee080
      with:
        protocol: tcp
        port: 5901
    - name: Change runner password
      run: |
         sudo apt-get update 
         echo 'runner:${{ secrets.PASSWORD }}' | sudo chpasswd
         echo 'runneradmin:${{ secrets.PASSWORD }}' | sudo chpasswd

    - name: Install desktop environment 
      run: |
        sudo apt-get install xfce4 xfce4-terminal -y 

    - name: Install and configure vnc4server
      run: |
        sudo apt-get install vnc4server -y

        su runner -c 'mkdir -p ~/.vnc'
        su runner -c 'printf "#!/bin/bash\nstartxfce4 &" > ~/.vnc/xstartup'
        su runner -c "vncpasswd <<EOF
        ${{ secrets.PASSWORD }}
        ${{ secrets.PASSWORD }}
        n
        EOF"
        
        su runneradmin -c 'mkdir -p ~/.vnc'
        su runneradmin -c 'printf "#!/bin/bash\nstartxfce4 &" > ~/.vnc/xstartup'
        su runneradmin -c "vncpasswd <<EOF
        ${{ secrets.PASSWORD }}
        ${{ secrets.PASSWORD }}
        n
        EOF"
    
    - name: Run VNC
      run: |
        vnc4server -httpport 5901 &

    - name: sleep
      run: sleep 21600